### PR TITLE
Slovakian translation

### PR DESCRIPTION
**Pull request by tobias-klein**
This pull request contains the Slovakian translation changes submitted by martin-sk.

### CODE REVIEW

**Comment by tobias-klein** [comment]
The following strings still miss a translation - is that intentional?

- "sword-module-info": "SWORD Module Info"
- "sword-unlock-info": "SWORD Unlock Info"
- "sword-library-info": "SWORD Library Info"
- "module-hebrew-strongs-dict": "Hebrew Strong's"
- "module-greek-strongs-dict": "Greek Strong's"
- "tag-filter": "Filter: "

**Comment by tobias-klein** [comment]
@MartinIIOT Any feedback?

**Comment by tobias-klein** [comment]
@MartinIIOT
Still waiting for your feedback.

**Comment by MartinIIOT** [comment]
Yes, strings are OK

**Comment by tobias-klein** [comment]
> Yes, strings are OK.
> (Sorry for the later reply)

Thanks! Would you mind getting in touch with me as well via e-mail (see the email address in the [README.md](https://github.com/ezra-project/ezra-project/blob/master/README.md) file). I need to be able to contact you for future releases for translation coordination purposes.

**Comment by tobias-klein** [comment]
@MartinIIOT 
I added one more string to the translation file which had been recently added on master: `show-header-navigation`
This is related to #112. Could you add a translation for that string?

**Review by MartinIIOT — CHANGES_REQUESTED** [review]
Zobraziť navigáciu v hlavičke

**Review by MartinIIOT — DISMISSED** [review]

**Pull request merged**
